[build]
command = "yarn deploy"
functions = "functions"
publish = "_site"

[dev]
command = "yarn dev"

[[redirects]]
from = "/admin/*"
to = "/.netlify/functions/dynamic"
force = true
status = 200
_generated_by_eleventy_serverless = "dynamic"

  [redirects.conditions]
  Role = [ "admin" ]

[[redirects]]
from = "/admin/*"
to = "/login/"
force = true
status = 401

[[plugins]]
package = "netlify-plugin-inline-functions-env"

  [plugins.inputs]
  include = [ "CONTEXT" ]
