[build]
command = "yarn deploy"
functions = "functions"
publish = "_site"

[dev]
command = "yarn dev"

[[redirects]]
from = "/admin/*"
force = true
status = 200
conditions = {Role = ["admin"]}

[[redirects]]
from = "/admin/*"
to = "/login/"
force = true
status = 401

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[plugins]]
package = "netlify-plugin-inline-functions-env"

  [plugins.inputs]
  include = [ "CONTEXT" ]
